[package]
name = "malachite"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite"
path = "src/lib.rs"

[dependencies]
malachite-base = { path = "../malachite-base" }
malachite-gmp = { path = "../malachite-gmp", optional = true }
malachite-native = { path = "../malachite-native", optional = true }
rand = "0.3.0"

[features]
default = []
gmp = ["malachite-gmp"]
native = ["malachite-native"]
