[package]
name = "malachite"
version = "0.3.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]
rust-version = "1.61.0"
edition = "2021"
description = "Arbitrary-precision arithmetic, with efficient algorithms partially derived from GMP and FLINT"
readme = "../README.md"
homepage = "https://malachite.rs/"
repository = "https://github.com/mhogrefe/malachite"
license = "LGPL-3.0-only"
keywords = ["mathematics", "math", "numerics", "bignum"]
categories = ["mathematics"]

[dependencies]
malachite-base = "0.3.0"
malachite-nz = { version = "0.3.0", optional = true }
malachite-q = { version = "0.3.0", optional = true }
serde = { version = "^1.0.0", optional = true, features = ["derive"] }

[features]
default = [ "naturals_and_integers", "rationals" ]
enable_serde = [ "malachite-q/enable_serde", "malachite-nz/enable_serde" ]
naturals_and_integers = [ "malachite-nz" ]
rationals = [ "malachite-q" ]
