[package]
name = "malachite-nz"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_nz"
path = "src/lib.rs"

[features]
32_bit_limbs = []
fail_on_untested_path = []

[dependencies]
itertools = "0.9.0"
malachite-base = { path = "../malachite-base" }
serde = { version = "^1.0.0", optional = true, features = ["derive"] }

[profile.release]
lto = true
strip = "debuginfo"

[dev-dependencies]
num = "0.4.0"
malachite-base-test-util = { path = "../malachite-base-test-util" }
malachite-nz-test-util = { path = "../malachite-nz-test-util" }
serde = "^1.0.0"
serde_json = "^1.0.32"

[dev-dependencies.rug]
version = "1.14.1"
default-features = false
features = ["integer"]

