[package]
name = "malachite-nz"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_nz"
path = "src/lib.rs"

[features]

32_bit_limbs = []

[dependencies]
malachite-base = { path = "../malachite-base" }
rand = "0.3.0"

serde = { version = "^1.0.0", optional = true, features = ["derive"] }

[profile.release]
lto = true
