[package]
name = "malachite-nz"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_nz"
path = "src/lib.rs"

[[bin]]
name = "malachite_nz_main"
path = "src/bin.rs"

[dependencies]
itertools = "0.9.0"
malachite-base = { path = "../malachite-base" }
serde = { version = "^1.0.0", optional = true, features = ["derive"] }

serde_json = { version = "^1.0.32", optional = true }
num = { version = "0.4.0", optional = true, features = ["serde"] }
rug = { version = "1.14.1", default-features = false, optional = true, features = ["integer", "serde"] }

[features]
32_bit_limbs = []
test_build = ["malachite-base/test_build", "serde", "serde_json", "num", "rug"]

[profile.release]
lto = true
strip = true
