[package]
name = "malachite-nz"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_nz"
path = "src/lib.rs"

[features]
32_bit_limbs = []

[dependencies]
malachite-base = { path = "../malachite-base" }
rand = "0.4.6"
serde = { version = "^1.0.0", optional = true, features = ["derive"] }

[profile.release]
lto = true

[dev-dependencies]
num = "0.2.0"
malachite-base-test-util = { path = "../malachite-base-test-util" }

[dev-dependencies.rug]
version = "^1.2.0"
default-features = false
features = ["integer"]

