[package]
name = "malachite-criterion-bench"
version = "0.2.1"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]
autobenches = false

[dependencies]
malachite-base = { version = "0.2.1", default-features = false }
malachite-nz = { path = "../malachite-nz", default-features = false }
num = "0.4.0"
rug = { version = "1.14.1", default-features = false, features = ["integer", "serde"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "natural_mul"
harness = false
