[workspace]
members = ['malachite', 'malachite-base', 'malachite-float', 'malachite-nz', 'malachite-q', 'malachite-criterion-bench']
resolver = "2"

[workspace.dependencies]
malachite-base = { version = "0.4.14", path = 'malachite-base' }
malachite-nz = { version = "0.4.14", path = 'malachite-nz', default_features = false }
malachite-q = { version = "0.4.14", path = 'malachite-q' }
malachite-float = { version = "0.4.14", path = 'malachite-float' }

[profile.release]
lto = "fat"
strip = true
