[package]
name = "malachite-bigint"
version = "0.1.4"
authors = ["Steve Shi <shikangzhi@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A drop-in num-bigint replacement based on malachite"

[dependencies]
malachite = "0.3.2"
num-traits = { version = "0.2.11", default-features = false, features = ["i128"] }
num-integer = { version = "0.1.45", default-features = false, features = ["i128"] }
derive_more = "0.99.17"
paste = "1.0.12"
