[workspace]
members = ['malachite', 'malachite-base', 'malachite-nz', 'malachite-q', 'malachite-criterion-bench']

[workspace.dependencies]
malachite-base = { version = "0.3.2", path = 'malachite-base' }
malachite-nz = { version = "0.3.2", path = 'malachite-nz', default_features = false }
malachite-q = { version = "0.3.2", path = 'malachite-q' }

[profile.release]
lto = true
strip = true
