[workspace]
members = ['malachite', 'malachite-base', 'malachite-float', 'malachite-nz', 'malachite-q', 'malachite-criterion-bench']
resolver = "2"

[workspace.dependencies]
malachite-base = "0.4.1"
malachite-nz = { version = "0.4.1",  default_features = false }
malachite-q = "0.4.1"
malachite-float = "0.4.1"

[profile.release]
lto = true
strip = true
