[package]
name = "malachite-test"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_test"
path = "src/lib.rs"

[[bin]]
name = "malachite_test_main"
path = "src/bin.rs"

[dependencies]
malachite-base = { path = "../malachite-base" }
malachite-nz = { path = "../malachite-nz", features = ["serde"] }
rust-wheels = { path = "../../rust-wheels" }
num = "0.1.37"
rand = "0.3.0"
serde = "1.0"
serde_json = "1.0"

[dependencies.rug]
version = "0.9.2"
default-features = false
features = ["integer"]
