[package]
name = "malachite-test"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_test"
path = "src/lib.rs"

[[bin]]
name = "malachite_test_main"
path = "src/bin.rs"

[dependencies]
malachite = { path = "../malachite" }
malachite-gmp = { path = "../malachite-gmp" }
malachite-native = { path = "../malachite-native" }
rust-wheels = { path = "../../rust-wheels" }
num = "0.1.37"
rand = "0.3.0"
rugint = "0.2.0"

[features]
default = ["malachite/gmp", "rust-wheels/gmp"]
