[package]
name = "malachite-native"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_native"
path = "src/lib.rs"

[dependencies]
malachite-base = { path = "../malachite-base" }
rand = "0.3.0"
