[package]
name = "malachite-base"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "malachite_base"
path = "src/lib.rs"

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
sha3 = "0.9.0"

[profile.release]
lto = true

[dev-dependencies]
malachite-base-test-util = { path = "../malachite-base-test-util" }
maplit = "1.0.2"
