[package]
name = "malachite-base"
version = "0.2.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]
rust-version = "1.61.0"
description = "A collection of utilities, including new arithmetic traits and iterators that generate all values of a type"
readme = "README.md"
homepage = "https://malachite.rs/"
repository = "https://github.com/mhogrefe/malachite"
license = "LGPL-3.0"
keywords = ["mathematics", "math", "numerics", "testing"]
categories = ["mathematics", "development-tools::testing"]

[lib]
name = "malachite_base"
path = "src/lib.rs"

[[bin]]
name = "malachite_base_main"
path = "src/bin.rs"
test = false

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
ryu = "1.0"
sha3 = "0.9.0"

clap = { version = "2.33.1", optional = true }
gnuplot = { version = "0.0.26", optional = true }
time = { version = "0.1.40", optional = true }
walkdir = { version = "2", optional = true }

[features]
test_build = ["gnuplot", "time", "clap"]
bin_build = ["walkdir", "test_build"]

[profile.release]
lto = true
strip = true

[dev-dependencies]
maplit = "1.0.2"

[badges]
maintenance = { status = "actively-maintained" }
