[package]
name = "malachite-bench"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]
edition = "2018"

[lib]
name = "malachite_bench"
path = "src/lib.rs"

[dependencies]
streaming-stats = "0.2.2"
time = "0.1.40"

[profile.release]
lto = true
